
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_demoapi
    username: admin2024
    password: Admin2024
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
  logging:
    level:
      org:
        hibernate:
          type: trace
